# Generated by Django 4.2.1 on 2023-05-13 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('time_taken', models.DurationField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clue_1_completed', models.BooleanField(default=False)),
                ('clue_1_time', models.DurationField(blank=True, null=True)),
                ('clue_2_completed', models.BooleanField(default=False)),
                ('clue_2_time', models.DurationField(blank=True, null=True)),
                ('clue_3_completed', models.BooleanField(default=False)),
                ('clue_3_time', models.DurationField(blank=True, null=True)),
                ('clue_4_completed', models.BooleanField(default=False)),
                ('clue_4_time', models.DurationField(blank=True, null=True)),
                ('clue_5_completed', models.BooleanField(default=False)),
                ('clue_5_time', models.DurationField(blank=True, null=True)),
                ('deadend_1_time', models.DurationField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
