# Generated by Django 4.2.1 on 2023-05-15 19:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_logic', '0002_game_deadend_2_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='clue_1_time',
            field=models.DurationField(default=datetime.timedelta(0), null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='clue_2_time',
            field=models.DurationField(default=datetime.timedelta(0), null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='clue_3_time',
            field=models.DurationField(default=datetime.timedelta(0), null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='clue_4_time',
            field=models.DurationField(default=datetime.timedelta(0), null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='clue_5_time',
            field=models.DurationField(default=datetime.timedelta(0), null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deadend_1_time',
            field=models.DurationField(default=datetime.timedelta(0), null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='deadend_2_time',
            field=models.DurationField(default=datetime.timedelta(0), null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='time_taken',
            field=models.DurationField(default=datetime.timedelta(0), null=True),
        ),
    ]
